# Generated by Django 6.0.3 on 2026-05-02 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nyondogeneralhardwareapp', '0002_supplier_alter_stock_supplier_supply'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Supply',
        ),
    ]
