# Generated by Django 6.0.3 on 2026-05-03 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nyondogeneralhardwareapp', '0003_delete_supply'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='payment_terms',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Credit', 'Credit')], default='Cash', max_length=10),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='credit_terms',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
