# Generated by Django 6.0.3 on 2026-05-03 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nyondogeneralhardwareapp', '0004_supplier_payment_terms_alter_supplier_credit_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='unit',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
