# Generated by Django 6.0.3 on 2026-05-04 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nyondogeneralhardwareapp', '0006_supplier_is_active_alter_stock_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
