# Generated by Django 6.0.3 on 2026-05-07 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nyondogeneralhardwareapp', '0010_remove_sale_product_remove_sale_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='specification',
        ),
        migrations.AddField(
            model_name='saleitem',
            name='stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='nyondogeneralhardwareapp.stock'),
        ),
    ]
