# Generated by Django 6.0.3 on 2026-05-07 07:31

from django.db import migrations

def link_saleitems_to_stock(apps, schema_editor):
    SaleItem = apps.get_model("nyondogeneralhardwareapp", "SaleItem")
    Stock = apps.get_model("nyondogeneralhardwareapp", "Stock")

    for item in SaleItem.objects.all():
        try:
            stock = Stock.objects.get(
                product_name=item.product,        # old text field
                specification=item.specification  # old text field
            )
            item.stock_id = stock.id             # new ForeignKey field
            item.save()
        except Stock.DoesNotExist:
            # If no match, leave null or fix manually later
            pass
class Migration(migrations.Migration):

    dependencies = [
        ('nyondogeneralhardwareapp', '0011_remove_saleitem_product_and_more'),
    ]

    operations = [
    ]
