# Generated by Django 6.0.3 on 2026-05-07 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nyondogeneralhardwareapp', '0012_auto_20260507_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleitem',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nyondogeneralhardwareapp.stock'),
        ),
    ]
