# Generated by Django 6.0.5 on 2026-05-13 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nyondogeneralhardwareapp', '0016_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreceipt',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='goodsreceipt',
            name='collection',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='nyondogeneralhardwareapp.goodscollection'),
        ),
    ]
