# Generated by Django 6.0.5 on 2026-05-13 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nyondogeneralhardwareapp', '0017_goodsreceipt_total_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodscollection',
            name='product',
        ),
        migrations.AddField(
            model_name='goodscollection',
            name='stock',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='nyondogeneralhardwareapp.stock'),
        ),
        migrations.AlterField(
            model_name='goodsreceipt',
            name='collection',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='nyondogeneralhardwareapp.goodscollection'),
        ),
    ]
