# Generated by Django 6.0.5 on 2026-05-19 07:57

import django.core.validators
import nyondogeneralhardwareapp.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nyondogeneralhardwareapp', '0019_stock_total_cost_suppliercredit_supplierpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='nin',
            field=models.CharField(max_length=14, unique=True, validators=[nyondogeneralhardwareapp.validators.validate_ugandan_national_id]),
        ),
        migrations.AlterField(
            model_name='participant',
            name='phone',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Phone number must start with +256 and contain 9 digits (e.g. +256760752349).', regex='^+256\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='sale',
            name='customer_phone',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Phone number must start with +256 and contain 9 digits (e.g. +256760752349).', regex='^+256\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='contact_number',
            field=models.CharField(blank=True, max_length=13, validators=[django.core.validators.RegexValidator(message='Phone number must start with +256 and contain 9 digits (e.g. +256760752349).', regex='^+256\\d{9}$')]),
        ),
    ]
