# Generated by Django 6.0.5 on 2026-05-19 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nyondogeneralhardwareapp', '0020_alter_participant_nin_alter_participant_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='contact_number',
            field=models.CharField(blank=True, max_length=9),
        ),
    ]
