# Generated by Django 6.0.5 on 2026-05-19 09:39

import django.core.validators
import nyondogeneralhardwareapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nyondogeneralhardwareapp', '0022_alter_stock_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='quantity',
            field=models.IntegerField(validators=[nyondogeneralhardwareapp.models.validate_positive]),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='contact_number',
            field=models.CharField(blank=True, max_length=9, validators=[django.core.validators.RegexValidator(message='Phone number must start with +256 and contain 9 digits (e.g. +256760752349).', regex='^+256\\d{9}$')]),
        ),
    ]
