# Generated by Django 6.0.5 on 2026-05-19 09:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nyondogeneralhardwareapp', '0023_alter_stock_quantity_alter_supplier_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='phone',
            field=models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='Phone number must start with +256 and contain 9 digits (e.g. +256760752349).', regex='^+256\\d{9}$')]),
        ),
    ]
