# Generated by Django 6.0.5 on 2026-05-19 12:03

import django.core.validators
import nyondogeneralhardwareapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nyondogeneralhardwareapp', '0024_alter_participant_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[nyondogeneralhardwareapp.models.validate_positive]),
        ),
        migrations.AlterField(
            model_name='goodscollection',
            name='quantity',
            field=models.IntegerField(validators=[nyondogeneralhardwareapp.models.validate_positive]),
        ),
        migrations.AlterField(
            model_name='participant',
            name='phone',
            field=models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='Phone number must start with +256 and contain 9 digits (e.g. +256760752349).', regex='^\\+256\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='sale',
            name='customer_phone',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Phone number must start with +256 and contain 9 digits (e.g. +256760752349).', regex='^\\+256\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='sale',
            name='distance_km',
            field=models.IntegerField(default=0, validators=[nyondogeneralhardwareapp.models.validate_positive]),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='quantity',
            field=models.IntegerField(validators=[nyondogeneralhardwareapp.models.validate_positive]),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[nyondogeneralhardwareapp.models.validate_positive]),
        ),
        migrations.AlterField(
            model_name='stock',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[nyondogeneralhardwareapp.models.validate_positive]),
        ),
        migrations.AlterField(
            model_name='stock',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[nyondogeneralhardwareapp.models.validate_positive]),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='contact_number',
            field=models.CharField(blank=True, max_length=9, validators=[django.core.validators.RegexValidator(message='Phone number must start with +256 and contain 9 digits (e.g. +256760752349).', regex='^\\+256\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='suppliercredit',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[nyondogeneralhardwareapp.models.validate_positive]),
        ),
        migrations.AlterField(
            model_name='supplierpayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[nyondogeneralhardwareapp.models.validate_positive]),
        ),
    ]
