# Generated by Django 6.0.5 on 2026-05-21 09:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nyondogeneralhardwareapp', '0025_alter_deposit_amount_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='contact_number',
            field=models.CharField(blank=True, max_length=13, validators=[django.core.validators.RegexValidator(message='Phone number must start with +256 and contain 9 digits (e.g. +256760752349).', regex='^\\+256\\d{9}$')]),
        ),
    ]
