# Generated by Django 6.0.5 on 2026-06-02 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nyondogeneralhardwareapp', '0026_alter_supplier_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='date_registered',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='registered_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
